### ISSUE TITLE
Add support for recent solidity compiler versions

### ISSUE THREAD

**Issue by beeb** [syntest-framework/syntest-solidity#119]
**Describe the bug**
I'm using the somewhat recent `unchecked` context (new in solidity 0.8.0) in my contract and it makes syntest fail with a `ParserError`.

```
Trace: ParserError: missing ';' at '{' (5:18)
```

**To Reproduce**
Create a contract that uses the `unchecked` instruction with solidity version >= 0.8.0.

```solidity
contract Test {
    function uncheckedInc(uint256 i) internal pure returns (uint256) {
        unchecked {
            return i + 1;
        }
    }
}
```
Try to run `syntest-solitity` as described in README.

**Expected behavior**
Should work

**Screenshots**

**Environment information (please complete the following information):**

- OS: Ubuntu 20.04
- Version 0.1.2

**Additional context**

**Comment by beeb** [comment]
I suspect it's a simple matter of upgrading to the latest version of `@solidity-parser/parser`

**Comment by mitchellolsthoorn** [comment]
@beeb Thank you for making an issue and making us aware of this problem! I have investigated this issue over the last few days but did not manage to fully fix the problem yet.

As you mentioned updating the `@solidity-parser/parser` solves the error of parsing the smart contract for analysis. It then gave a compilation error as Truffle was using the wrong `solc` version for compilation. I solved this by configuring the tool to detect the pragma statement in the contract and automatically selecting the correct compiler version to use.

Currently, I am figuring out an error thrown by Truffle:
```
TypeError: Cannot destructure property 'contractName' of 'contract' as it is undefined.
```
This problem seems to be with Truffle and I have already updated it to the latest version.

I will keep investigating this issue and keep you up to date of my findings
